global:
  slack_api_url: 'https://hooks.slack.com/services/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QO8'
  resolve_timeout: 5m
  smtp_smarthost: 'mail.gmail.com:587'
  smtp_from: 'account@gmail.com'
  smtp_auth_username: 'account@gmail.com'
  smtp_auth_password: 'PassworD'

route:
  
  receiver: 'slack-notifications'
  repeat_interval: 5m
  group_interval: 5m
  routes:
    - receiver: 'smtp-receiver'

receivers:
- name: 'slack-notifications'
  slack_configs:
  - channel: '#chanel_slack'
- name: 'smtp-receiver'
  email_configs:
  - to: mail@gmail.com
