FROM ruby:2.2-alpine


ENV APP_HOME /app
RUN mkdir $APP_HOME
WORKDIR $APP_HOME
ADD . $APP_HOME

RUN apk add --virtual .build --no-cache  build-base libffi-dev \
	&& bundle install \
	&& apk del .build


ENV COMMENT_DATABASE_HOST comment_db
ENV COMMENT_DATABASE comments


CMD ["puma"]

