version: '3.3'


services:
  post_db:
    image: mongo:${MONGODB_V}
    volumes:
      - post_db:/data/db
    networks:
      back_net:
       aliases:
        - post_db
        - comment_db

  ui:
    image: ${USERNAME}/ui
    hostname: reddit-app
    ports:
      - ${HOST_PORT}:9292
    networks:
      - front_net

  post:
    image: ${USERNAME}/post
    networks:
      back_net:
       aliases:
        - post
      front_net:
       aliases:
        - post

  comment:
    image: ${USERNAME}/comment
    networks:
      front_net:
        aliases:
          - comment
      back_net:
        aliases:
          - comment
   
volumes:
  post_db:

networks:
    front_net:
      external:
        name: front_net
    back_net:
      external:
        name: back_net
