{
 "title": "UI Service Monitoring",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "HTTP responce time 95th percentile",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(ui_request_response_time_bucket[1m])) by(le))"
    }
   ]
  },
  {
   "title": "Rate of UI HTTP Requests with Error",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(ui_request_count{http_status=~\"^[45].*\"}[1m])"
    }
   ]
  },
  {
   "title": "Rate of UI HTTP Request without errors",
   "type": "graph",
   "description": "[2XX] status HTTP request for UI services",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(ui_request_count{http_status=~\"^[2].*\"}[1m])"
    }
   ]
  }
 ]
}