---
- name: Create GCE instance
  hosts: localhost
  tasks:
   - name: Create controllers
     become: true
     become_user: admin
     shell: |
       for i in 0 1 2; do
          gcloud compute instances create controller-${i} \
           --async \
           --boot-disk-size 200GB \
           --can-ip-forward \
           --image-family ubuntu-1804-lts \
           --image-project ubuntu-os-cloud \
           --machine-type n1-standard-1 \
           --private-network-ip 10.240.0.1${i} \
           --scopes compute-rw,storage-ro,service-management,service-control,logging-write,monitoring \
           --subnet kubernetes \
           --tags kubernetes-the-hard-way,controller
       done     
     args:
        executable: /bin/bash
        warn: False
     tags:
       - create_hosts
   - name: Create workers      
     become: true
     become_user: admin
     shell: |
       for i in 0 1 2; do
         gcloud compute instances create worker-${i} \
           --async \
           --boot-disk-size 200GB \
           --can-ip-forward \
           --image-family ubuntu-1804-lts \
           --image-project ubuntu-os-cloud \
           --machine-type n1-standard-1 \
           --metadata pod-cidr=10.200.${i}.0/24 \
           --private-network-ip 10.240.0.2${i} \
           --scopes compute-rw,storage-ro,service-management,service-control,logging-write,monitoring \
           --subnet kubernetes \
           --tags kubernetes-the-hard-way,worker
       done
     args:
        executable: /bin/bash
        warn: False
     tags:
       - create_hosts


   - name: Get list  the instance
     shell: "gcloud compute instances list"
     register: gce_instance
     tags:
       - create_hosts
   - name: List the instance
     debug:
       var: gce_instance.stdout
     tags:
       - create_hosts

   - name: Refresh inventory to ensure new instaces exist in inventory
     meta: refresh_inventory
     tags:
       - create_hosts

