---
- name: Deploy the coredns cluster add-on
  hosts: localhost
  become: true
  become_user: admin
  tasks:
   - name: 
     shell: |
       kubectl apply -f https://storage.googleapis.com/kubernetes-the-hard-way/coredns.yaml
       kubectl get pods -l k8s-app=kube-dns -n kube-system
     args:
        executable: /bin/bash
        warn: False
     register: pod_coredns
     tags:
       - pod_coredns
   - debug: var=pod_core.stdout
