groups:
  - name: alert.rules
    rules:
    - alert: InstanceDown
      expr: up == 0
      for: 1m
      labels:
        severity: warning
      annotations:
        description: '{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 1 minute'
        summary: 'Instance {{ $labels.instance }} down'
    - alert: HttpRequestError
      expr: rate(ui_request_count{http_status=~"^[45].*"}[1m]) > 0.1
      labels:
        severity: info
      annotations:
        description: '{{ $labels.instance }} of job {{ $labels.job }} send many http 4XX code'
        summary: 'Many http error in {{ $labels.instance }}'
