kind: EncryptionConfig
apiVersion: v1
resources:
  - resources:
      - secrets
    providers:
      - aescbc:
          keys:
            - name: key1
              secret: PZJZvPjOcO+vX5mJyRks/9IJpSvlkESZyl2rOBNpDd0=
      - identity: {}
